"use client";
import React from "react";
import _styles from "./css/classes.module.css";
import * as _utils from "./utils";
import Block from "./_Builtin/Block";
import Grid from "./_Builtin/Grid";
import Heading from "./_Builtin/Heading";
import HtmlEmbed from "./_Builtin/HtmlEmbed";
import Image from "./_Builtin/Image";
import Link from "./_Builtin/Link";
import Paragraph from "./_Builtin/Paragraph";
import TabsContent from "./_Builtin/TabsContent";
import TabsLink from "./_Builtin/TabsLink";
import TabsMenu from "./_Builtin/TabsMenu";
import TabsPane from "./_Builtin/TabsPane";
import TabsWrapper from "./_Builtin/TabsWrapper";
import * as _interactions from "./interactions";
import { ArrowLearn } from "./ArrowLearn";
import { ArrowRunCta } from "./ArrowRunCta";

const _interactionsData = JSON.parse(
  '{"events":{"e-5053":{"id":"e-5053","name":"","animationType":"custom","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5054"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ef","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ef","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394128852},"e-5054":{"id":"e-5054","name":"","animationType":"custom","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5053"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ef","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ef","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394128862},"e-5055":{"id":"e-5055","name":"","animationType":"custom","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5056"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5f2","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5f2","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394243474},"e-5056":{"id":"e-5056","name":"","animationType":"custom","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5055"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5f2","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5f2","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394243479},"e-5057":{"id":"e-5057","name":"","animationType":"custom","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5058"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ec","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ec","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394257282},"e-5058":{"id":"e-5058","name":"","animationType":"custom","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5057"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ec","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"68de1c4094b1bf9ae5de7e6b|195ff874-5080-2c32-1c5c-464c3cf2d5ec","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759394257291},"e-5291":{"id":"e-5291","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5292"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d3a2","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d3a2","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5292":{"id":"e-5292","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5291"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d3a2","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d3a2","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5293":{"id":"e-5293","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5294"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5294":{"id":"e-5294","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5293"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5295":{"id":"e-5295","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5296"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39f","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39f","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5296":{"id":"e-5296","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5295"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39f","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"d02eca62-6d39-2e61-d16a-e87b5c31d39f","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1759944273192},"e-5531":{"id":"e-5531","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-528","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5532"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e68","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e68","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5532":{"id":"e-5532","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-529","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5531"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e68","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e68","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5533":{"id":"e-5533","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-528","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5534"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e62","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e62","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5534":{"id":"e-5534","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-529","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5533"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e62","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e62","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5535":{"id":"e-5535","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-528","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5536"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e65","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e65","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5536":{"id":"e-5536","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-529","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5535"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e65","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"691d5bd02b8ecc8d4c6a2508|8158cc01-78aa-38a6-7cfc-7b30bad25e65","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1763550420318},"e-5547":{"id":"e-5547","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5548"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e0d","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e0d","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781},"e-5548":{"id":"e-5548","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5547"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e0d","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e0d","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781},"e-5549":{"id":"e-5549","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5550"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e10","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e10","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781},"e-5550":{"id":"e-5550","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5549"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e10","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e10","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781},"e-5551":{"id":"e-5551","name":"","animationType":"preset","eventTypeId":"TAB_ACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-509","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5552"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e13","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e13","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781},"e-5552":{"id":"e-5552","name":"","animationType":"preset","eventTypeId":"TAB_INACTIVE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-510","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-5551"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e13","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"69281e787f324401152956be|80bb0706-9b43-4a08-c8dd-213e31cb0e13","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1764236954781}},"actionLists":{"a-509":{"id":"a-509","title":"home-new_tabs-in","actionItemGroups":[{"actionItems":[{"id":"a-509-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":640,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]},{"actionItems":[{"id":"a-509-n-2","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"easeIn","duration":800,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":0,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]}],"useFirstGroupAsInitialState":true,"createdOn":1759394134609},"a-510":{"id":"a-510","title":"home-new_tabs-out","actionItemGroups":[{"actionItems":[{"id":"a-510-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"easeIn","duration":0,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":640,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]}],"useFirstGroupAsInitialState":false,"createdOn":1759394134609},"a-528":{"id":"a-528","title":"home-new_tabs-in 2","actionItemGroups":[{"actionItems":[{"id":"a-528-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":640,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]},{"actionItems":[{"id":"a-528-n-2","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"easeIn","duration":800,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":0,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]}],"useFirstGroupAsInitialState":true,"createdOn":1759394134609},"a-529":{"id":"a-529","title":"home-new_tabs-out 2","actionItemGroups":[{"actionItems":[{"id":"a-529-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"easeIn","duration":0,"target":{"useEventTarget":"CHILDREN","selector":".new-home_tab-pane","selectorGuids":["7b456de1-8461-6c6b-6076-ea463eb27edb"]},"xValue":null,"yValue":640,"xUnit":"px","yUnit":"px","zUnit":"PX"}}]}],"useFirstGroupAsInitialState":false,"createdOn":1759394134609}},"site":{"mediaQueries":[{"key":"main","min":992,"max":10000},{"key":"medium","min":768,"max":991},{"key":"small","min":480,"max":767},{"key":"tiny","min":0,"max":479}]}}'
);

export function ProductTab({ as: _Component = Block, variant = "Base" }) {
  _interactions.useInteractions(_interactionsData, _styles);

  const _styleVariantMap = {
    Base: "",
    "No - title": "w-variant-4f9daab2-de75-926c-9cd6-cbe00802e362",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <_Component
      className={_utils.cx(_styles, "new-home-tab_wrap", _activeStyleVariant)}
      tag="div"
    >
      <Block
        className={_utils.cx(
          _styles,
          "row",
          "is-vertical",
          "align_center",
          "gap-20",
          "product_title",
          _activeStyleVariant
        )}
        tag="div"
      >
        <Block
          className={_utils.cx(
            _styles,
            "row",
            "is-vertical",
            "align_center",
            "gap-12",
            _activeStyleVariant
          )}
          id={_utils.cx(
            _styles,
            "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d393-5c31d391"
          )}
          tag="div"
        >
          <Block
            className={_utils.cx(
              _styles,
              "sub-title-18px",
              "n",
              "text_center",
              _activeStyleVariant
            )}
            tag="div"
          >
            {"Products"}
          </Block>
          <Heading
            className={_utils.cx(
              _styles,
              "new-home-tab_h2",
              _activeStyleVariant
            )}
            tag="h3"
          >
            {"Powering every corner of your workforce"}
          </Heading>
        </Block>
        <Paragraph
          className={_utils.cx(
            _styles,
            "new-home-tab_h2-para",
            _activeStyleVariant
          )}
        >
          {
            "Streamline every aspect of your construction workforce management workflow."
          }
        </Paragraph>
      </Block>
      <TabsWrapper
        className={_utils.cx(_styles, "hero-tab", _activeStyleVariant)}
        current="Payroll"
        easing="ease-in-quad"
        fadeIn={300}
        fadeOut={100}
      >
        <TabsMenu
          className={_utils.cx(
            _styles,
            "new-home_tabs-menu",
            _activeStyleVariant
          )}
          tag="div"
        >
          <TabsLink
            block="inline"
            className={_utils.cx(
              _styles,
              "new-home_tabs-link",
              _activeStyleVariant
            )}
            data-w-id="d02eca62-6d39-2e61-d16a-e87b5c31d39c"
            data-w-tab="Payroll"
          >
            <Block tag="div">{"Payroll"}</Block>
          </TabsLink>
          <TabsLink
            block="inline"
            className={_utils.cx(
              _styles,
              "new-home_tabs-link",
              _activeStyleVariant
            )}
            data-w-id="d02eca62-6d39-2e61-d16a-e87b5c31d39f"
            data-w-tab="HR Management"
          >
            <Block tag="div">{"HR Management"}</Block>
          </TabsLink>
          <TabsLink
            block="inline"
            className={_utils.cx(
              _styles,
              "new-home_tabs-link",
              _activeStyleVariant
            )}
            data-w-id="d02eca62-6d39-2e61-d16a-e87b5c31d3a2"
            data-w-tab="Productivity"
          >
            <Block tag="div">{"Productivity"}</Block>
          </TabsLink>
        </TabsMenu>
        <TabsContent
          className={_utils.cx(
            _styles,
            "hero-tab-content",
            "show",
            _activeStyleVariant
          )}
          tag="div"
        >
          <TabsPane
            className={_utils.cx(
              _styles,
              "new-home_tab-pane",
              _activeStyleVariant
            )}
            data-w-tab="Payroll"
            tag="div"
          >
            <Grid
              className={_utils.cx(
                _styles,
                "hero-tab_grid",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "hero_tab_iner-wrap",
                  _activeStyleVariant
                )}
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3a8-5c31d391"
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "row",
                    "is-vertical",
                    "gap-16",
                    "mobile_center",
                    _activeStyleVariant
                  )}
                  id={_utils.cx(
                    _styles,
                    "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3a9-5c31d391"
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "row",
                      "is-vertical",
                      "gap-8",
                      "mobile_center",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3aa-5c31d391"
                    )}
                    tag="div"
                  >
                    <Block
                      className={_utils.cx(
                        _styles,
                        "sub-title-18px",
                        "n",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      {"Construction Payroll"}
                    </Block>
                    <Heading
                      className={_utils.cx(
                        _styles,
                        "new-home-tab_h3",
                        "mobile-center",
                        _activeStyleVariant
                      )}
                      tag="h2"
                    >
                      {
                        "Manage construction payroll, overtime, prevailing wages and union compliance."
                      }
                    </Heading>
                  </Block>
                  <Paragraph
                    className={_utils.cx(
                      _styles,
                      "new-home-tab_para-18px",
                      "mobile-center",
                      _activeStyleVariant
                    )}
                  >
                    {
                      "Forget spreadsheets and focus on building. Lumber handles certified payroll, prevailing wages, union reporting, and tax filing—cutting processing time by 95% while ensuring fast, accurate, and compliant paychecks."
                    }
                  </Paragraph>
                </Block>
                <Grid
                  className={_utils.cx(
                    _styles,
                    "new-home-tab_grid",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Prevailing Wages"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3b6-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Certified Payroll"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3ba-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Union Reporting"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3be-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Worker Compensation"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      "ea",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3c2-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"401k Integration"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      "ca",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3c6-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Tax Filing"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      "ea",
                      "ca",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3ca-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Expense Management"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      "ea",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3ce-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Payroll Card"}</Block>
                  </Block>
                </Grid>
                <Block
                  className={_utils.cx(
                    _styles,
                    "button-holder",
                    "no-pad",
                    "mobile_center",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <ArrowRunCta
                    link={{
                      href: "#",
                    }}
                    text="Book a demo"
                  />
                  <Link
                    block="inline"
                    button={false}
                    className={_utils.cx(
                      _styles,
                      "learn-more_cta",
                      _activeStyleVariant
                    )}
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag="div">{"Learn more"}</Block>
                    <HtmlEmbed
                      className={_utils.cx(
                        _styles,
                        "icon",
                        _activeStyleVariant
                      )}
                      content=""
                      value="%3Csvg%20width%3D%2221%22%20height%3D%2220%22%20viewBox%3D%220%200%2021%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M4.66699%2010.0001H16.3337M16.3337%2010.0001L10.5003%204.16675M16.3337%2010.0001L10.5003%2015.8334%22%20stroke%3D%22%23FF8F84%22%20stroke-width%3D%221.66667%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                    />
                  </Link>
                </Block>
              </Block>
              <Image
                alt="Manage construction payroll, overtime, prevailing wages and union compliance."
                height="auto"
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3d9-5c31d391"
                )}
                loading="lazy"
                src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68e50d4aecab974530a9e681_Construction%20Payroll-new.webp"
                width="562"
              />
            </Grid>
          </TabsPane>
          <TabsPane
            className={_utils.cx(
              _styles,
              "new-home_tab-pane",
              _activeStyleVariant
            )}
            data-w-tab="HR Management"
            tag="div"
          >
            <Grid
              className={_utils.cx(
                _styles,
                "hero-tab_grid",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "hero_tab_iner-wrap",
                  _activeStyleVariant
                )}
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3dc-5c31d391"
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "row",
                    "is-vertical",
                    "gap-16",
                    "mobile_center",
                    _activeStyleVariant
                  )}
                  id={_utils.cx(
                    _styles,
                    "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3dd-5c31d391"
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "row",
                      "is-vertical",
                      "gap-8",
                      "mobile_center",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3de-5c31d391"
                    )}
                    tag="div"
                  >
                    <Block
                      className={_utils.cx(
                        _styles,
                        "sub-title-18px",
                        "n",
                        "mobile-center",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      {"Construction Recruitment"}
                    </Block>
                    <Heading
                      className={_utils.cx(
                        _styles,
                        "new-home-tab_h3",
                        "mobile-center",
                        _activeStyleVariant
                      )}
                      tag="h2"
                    >
                      {
                        "Source skilled workers, verify credentials, and mobilize rapidly."
                      }
                    </Heading>
                  </Block>
                  <Paragraph
                    className={_utils.cx(
                      _styles,
                      "new-home-tab_para-18px",
                      "mobile-center",
                      _activeStyleVariant
                    )}
                  >
                    {
                      "Simplify workforce management with Lumber. From hiring and onboarding to benefits and credential tracking, all tailored for construction teams. Hire faster, retain talent, and maintain compliance—without the paperwork headache."
                    }
                  </Paragraph>
                </Block>
                <Grid
                  className={_utils.cx(
                    _styles,
                    "new-home-tab_grid",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Application Tracking System"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3ea-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Onboarding"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3ee-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Benefits Administration"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      "ea",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3f2-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Credential Management"}</Block>
                  </Block>
                </Grid>
                <Block
                  className={_utils.cx(
                    _styles,
                    "button-holder",
                    "no-pad",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <ArrowRunCta
                    link={{
                      href: "#",
                    }}
                    text="Book a demo"
                  />
                  <Link
                    block="inline"
                    button={false}
                    className={_utils.cx(
                      _styles,
                      "learn-more_cta",
                      _activeStyleVariant
                    )}
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag="div">{"Learn more"}</Block>
                    <HtmlEmbed
                      className={_utils.cx(
                        _styles,
                        "icon",
                        _activeStyleVariant
                      )}
                      content=""
                      value="%3Csvg%20width%3D%2221%22%20height%3D%2220%22%20viewBox%3D%220%200%2021%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M4.66699%2010.0001H16.3337M16.3337%2010.0001L10.5003%204.16675M16.3337%2010.0001L10.5003%2015.8334%22%20stroke%3D%22%23FF8F84%22%20stroke-width%3D%221.66667%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                    />
                  </Link>
                </Block>
              </Block>
              <Image
                alt="Source skilled workers, verify credentials, and mobilize rapidly."
                height="auto"
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d3fd-5c31d391"
                )}
                loading="lazy"
                src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de35b34f15cd7c9cce3995_Construction%20Recruitment.webp"
                width="562"
              />
            </Grid>
          </TabsPane>
          <TabsPane
            className={_utils.cx(
              _styles,
              "new-home_tab-pane",
              _activeStyleVariant
            )}
            data-w-tab="Productivity"
            tag="div"
          >
            <Grid
              className={_utils.cx(
                _styles,
                "hero-tab_grid",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "hero_tab_iner-wrap",
                  _activeStyleVariant
                )}
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d400-5c31d391"
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "row",
                    "is-vertical",
                    "gap-16",
                    "mobile_center",
                    _activeStyleVariant
                  )}
                  id={_utils.cx(
                    _styles,
                    "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d401-5c31d391"
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "row",
                      "is-vertical",
                      "gap-8",
                      "mobile_center",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d402-5c31d391"
                    )}
                    tag="div"
                  >
                    <Block
                      className={_utils.cx(
                        _styles,
                        "sub-title-18px",
                        "n",
                        "mobile-center",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      {"Productivity"}
                    </Block>
                    <Heading
                      className={_utils.cx(
                        _styles,
                        "new-home-tab_h3",
                        "mobile-center",
                        _activeStyleVariant
                      )}
                      tag="h3"
                    >
                      {
                        "Get real-time visibility into workforce, tasks, expenses and more."
                      }
                    </Heading>
                  </Block>
                  <Paragraph
                    className={_utils.cx(
                      _styles,
                      "new-home-tab_para-18px",
                      "mobile-center",
                      _activeStyleVariant
                    )}
                  >
                    {
                      "Gain total insight into field operations with Lumber. Track time, equipment, schedules, productivity, and safety—whether managing one crew or multiple sites. Build smarter, stay on schedule, and keep budgets intact."
                    }
                  </Paragraph>
                </Block>
                <Grid
                  className={_utils.cx(
                    _styles,
                    "new-home-tab_grid",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d40a-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Time Tracking"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d40e-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Productivity Tracking"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d412-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Recognition & Award"}</Block>
                  </Block>
                  <Block
                    className={_utils.cx(
                      _styles,
                      "new-home-point",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d416-5c31d391"
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de344dc61f475497323a97_Check%20icon.webp"
                      width="28.5"
                    />
                    <Block tag="div">{"Form Builder"}</Block>
                  </Block>
                </Grid>
                <Block
                  className={_utils.cx(
                    _styles,
                    "button-holder",
                    "no-pad",
                    "mobile_center",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <ArrowRunCta
                    link={{
                      href: "#",
                    }}
                    text="Book a demo"
                  />
                  <ArrowLearn />
                </Block>
              </Block>
              <Image
                alt="Get real-time visibility into workforce, tasks, expenses and more."
                height="auto"
                id={_utils.cx(
                  _styles,
                  "w-node-d02eca62-6d39-2e61-d16a-e87b5c31d41e-5c31d391"
                )}
                loading="lazy"
                src="https://cdn.prod.website-files.com/64ba4b61a6e0ed8004b57d97/68de3366e56f6c18c48ff9bd_Field%20Productivity.webp"
                width="562.5"
              />
            </Grid>
          </TabsPane>
        </TabsContent>
      </TabsWrapper>
    </_Component>
  );
}
